version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "strigus-lms-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xf72xdo8lkb1"
s3_prefix = "strigus-lms-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
